version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: install dependencies and environment
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Test with pytest
          command: |
            . venv/bin/activate
            pytest

workflows:
  main:
    jobs:
      - build-and-test